# Generated by Django 2.1.7 on 2019-03-25 15:16

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_readnote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.AlterModelOptions(
            name='readnote',
            options={},
        ),
        migrations.AddField(
            model_name='readnote',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True),
        ),
    ]
