# Generated by Django 2.1.7 on 2019-03-26 02:10

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_auto_20190325_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
