# Generated by Django 2.1.7 on 2019-03-26 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_auto_20190326_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='text',
        ),
    ]
