# Generated by Django 2.1.7 on 2019-03-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_remove_entry_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='readnote',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='readnote',
            name='topic',
            field=models.ForeignKey(on_delete=True, to='learning_logs.Books'),
        ),
    ]
